### Overview

In [ ]:
x = 50                      ### Variables
my_list = []                ### Lists
my_tuple = ()               ### Tuples
my_dictionary = {}          ### Dictionaries
array_a = np.array([])      ### N-D Arrays or N dimensional arrays. The object inside the brackets is converted with the np.array command to an array
series_a = pd.Series([])    ### Pandas Series . The object inside the brackets is converted with the pd.Series command to a series

data = {'':[],              ### Pandas Data Frames
        '':[],
        '':[]}


data = [{'':'','': ,'': },  ### More than one way to construct Data Frames
{'':'','': ,'': },
{'':'','': ,'': },
{'':'','': ,'': }]


df = pd.DataFrame(data)     ### The object data is converted with the command pd.DataFrame to a Data Frame
df                          ### Then you can call it with its name

### Variables


In [72]:
x = 50
y = 80
python = 45
x, y = 55, 85   ### This object will behave like a tuple


In [73]:
python
x, y

(55, 85)

### Lists

In [74]:
my_list = []
my_list_1 = ['John','Leila','Gregory','Kate']
my_list_1[2]

'Gregory'

### Tuples

In [75]:
my_tuple = ()
my_tuple = (50, 40, 60)
my_tuple

my_tuple_2 = 5, 6, 7                    ### Tuples can be withing lists
my_tuple_3 = 3, 5, 9                    ### You can also declare tuples without the brackets
my_list_2 = [my_tuple_2,my_tuple_3]
my_list_2                               ### Then each tuple becomes elements of the list


[(5, 6, 7), (3, 5, 9)]

### Dictionaries

In [76]:
my_dictionary = {}
my_dictionary_1 = {'key1': 'dog', 'key2': 'cat', 'key3': 'mouse', 'key4': 'fish'}
my_dictionary_2 = {'key1': 40, 'key2': 50, 'key3': 60, 'key4': 70}
print(my_dictionary_1['key1'])
my_dictionary_2['key3']

dog


60

### N-D arrays or N dimensional arrays

In [17]:
import numpy as np      ### N-D arrays are n dimeonsinal objects used in mathematical operations.
                        ### import function imports the module numpy that is needed to call an array and assigns it the letters np.
                        ### you can create an array now any time with the letters np.array

In [2]:
array_0 = np.array([4])   ### This is a one dimensional object or a scalar. In other words just a value.
array_0

array([4])

In [3]:
array_a = np.array([1,2,3])      ### Arrays can be thought of as vectors. This is a vector with 3 components.
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])       ### This array is a  2 by 2 matrix
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
type(array_b)

numpy.ndarray

### Pandas Series

In [5]:
import pandas as pd   ### don't forget to add pandas at the beginning if you are going to work with pandas and Data Frames

In [6]:
products = ['A', 'B', 'C', 'D']
type(products)

list

In [7]:
product_categories = pd.Series(products)
type(product_categories)

pandas.core.series.Series

In [8]:

series_a = pd.Series([10, 20, 30, 40, 50])
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Creating data frames as a dictionary of lists


In [11]:
import pandas as pd


data = {'Name':['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'],
        'Age':[50,53,35,43],
        'Working Experience (Yrs.)':[5,8,3,10]}
df = pd.DataFrame(data)
print(df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10


### As a list of dictionaries

In [12]:
import pandas as pd 


data = [{'Name':'Amy White','Age':50,'Working Experience (Yrs.)':5},
{'Name':'Jack Stewart','Age':53,'Working Experience (Yrs.)':8},
{'Name':'Richard Lauderdale','Age':35,'Working Experience (Yrs.)':3},
{'Name':'Sara Johnson','Age':43,'Working Experience (Yrs.)':10}]
df = pd.DataFrame(data)
print(df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10


### Creating Data frames from a list of dictionaries


In [13]:
data = [{'ProductName':'Product A', 'ProductPrice':22250}, 
        {'ProductName':'Product B', 'ProductPrice':16600}, 
        {'ProductName':'Product C', 'ProductPrice':12500}]
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

### Creating Data frames from a dictionary of pandas series

In [14]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'])
ser_prices = pd.Series([22250, 16600, 12500])

In [15]:
data = {'ProductName':ser_products, 'ProductPrice':ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

### Professional way

In [16]:
df = pd.DataFrame(data = [['Product A', 22250], ['Product B', 16600], ['Product C', 12500]], 
                  columns = ['ProductName', 'ProductPrice'],
                  index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500